### ISSUE TITLE
JS error if DokuWiki is configured to compress JS code

### ISSUE THREAD

**Issue by saschaleib** [fykosak/dokuwiki-plugin-cookielaw#18]
I noticed recently that when I get the cookielaw overlay, it can not be dismissed any more. In the browser console there is a JS error ("window not defined").

Then I disable JS compression (option "[compress](https://www.dokuwiki.org/config:compress)"), the plugin works again.

**Comment by Werkov** [comment]
Thanks for the report @saschaleib. Any chance you have other plugins that'd undefine `window` in their JS code (or could it be Dokuwiki's compressor fault)? Do you see any other references to `window` in the compressed Dokuwiki JS?

Cc: @cevro

**Comment by cevro** [comment]
This looks like, compression fault, it sometimes happens if prior loaded plugins script doesn't have ending semicolon. Please check if every (external too) scripts is ended by `;`. 

There is a one ugly protection, that every script files start with semicolon.

**Comment by saschaleib** [comment]
Actually, I found the problem, and indeed there was a semicolon issue, but not at the end of a script, but actually at the end of a block and before a root-level statement (where it only becomes a problem when all whitespace between them is removed). Better yet, the one to blame is ... myself. So this can be closed here - it is rather an issue for the compressor (or my template, which I will update in a few moments). Thanks for looking at this :-)
