### ISSUE TITLE
German translation - lang.php

### ISSUE THREAD

**Issue by Django-BOfH** [fykosak/dokuwiki-plugin-cookielaw#3]
<?php
/**
- German language file for cookielaw plugin
  *
- @author Michal Koutny michal@fykos.cz
  */

// custom language strings for the plugin
$lang['information'] = 'Cookies helfen bei der Bereitstellung von Inhalten. ' .
        'Durch die Nutzung dieser Seiten erklären Sie sich einverstanden, dass Cookies auf Ihrem Rechner gespeichert werden. ';
$lang['consent'] = 'OK';
$lang['details'] = ' Weitere Information';
$lang['details_url'] = 'https://de.wikipedia.org/wiki/Cookie';

//Setup VIM: ex: et ts=4 :

**Comment by Werkov** [comment]
Great! Could you please submit a PR?

**Comment by Django-BOfH** [comment]
I hope  my pull request is O.K. for you ...
