### ISSUE TITLE
doesn't work with farm setup

### ISSUE THREAD

**Issue by candardo** [fykosak/dokuwiki-plugin-cookielaw#9]
I've a dokuwiki setup which uses a _farm_ to manage different wikis with the same code (see [1]). This plugin works as expected with the _farmer_ (parent wiki, main installation) site but not with the _animals_ (child wikis, actual wiki pages). What's wrong:
- the banner is just a text line with a button
- clicking the button has no effect

I installed the plugin via the web interface. I'm running the last version of dokuwiki (tarball from their site) on an ARM debian server.

Attached are two images with the correct behaviour (farmer) and the wrong one (animals).
![cookielaw-animal](https://cloud.githubusercontent.com/assets/6369278/13723495/a788026e-e867-11e5-8d9f-e95c3f7eedbe.png)
![cookielaw-farmer](https://cloud.githubusercontent.com/assets/6369278/13723496/a7b10cae-e867-11e5-8845-442693499c3d.png)

Is there anything I can do to fix that?

Thanks!

[1] https://www.dokuwiki.org/farms

**Comment by candardo** [comment]
Purging the cache fixes the problem. 
Closing the issue.

**Comment by Werkov** [comment]
That sounds plausible. Thanks for figuring this out earlier than I could get down to it myself. :-)
